### ISSUE TITLE
having trouble when running the code

### ISSUE THREAD

**Issue by Chuyingithub97** [huiminren/ST-SiameseNet#2]
Hi, Thanks a lot for sharing the brilliant idea and the paper.
But I came across an issue when running the code.
I got the error information says in line 125, in main:
loss = siamese_net.train_on_batch(pair,label)
says:
ValueError: logits and labels must have the same shape ((1, 1) vs ())
How can I fix that?
Thank you very much!!

**Comment by gslxl** [comment]
co ask , I have the same problem with you !

**Comment by huiminren** [comment]
> Hi, Thanks a lot for sharing the brilliant idea and the paper.
> But I came across an issue when running the code.
> I got the error information says in line 125, in main:
> loss = siamese_net.train_on_batch(pair,label)
> says:
> ValueError: logits and labels must have the same shape ((1, 1) vs ())
> How can I fix that?
> Thank you very much!!

Hi, Thanks for being in interesting for our paper. I just tried the code locally again and it works for me. The error you got probably because of different version. I tested with python == 3.6.7, keras == 2.3.1 and tensorflow == 2.0.0.
Thanks.
